apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bidding-system.fullname" . }}-secret
  labels:
    {{- include "bidding-system.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.app.jwt.secret | b64enc | quote }}
  db-password: {{ .Values.postgresql.password | b64enc | quote }}
